name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn lint
      - run: yarn format-check
      - run: yarn build
      - run: 'git diff --quiet || (echo "Error: your branch is dirty\n" && git status --short && exit 1)'
